# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tutoriel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=500)),
                ('video', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courriel', models.CharField(max_length=64)),
                ('nom', models.CharField(max_length=16)),
                ('mdp', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='tutoriel',
            name='createur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitutos.Utilisateur'),
        ),
        migrations.AddField(
            model_name='note',
            name='tuto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_tuto', to='guitutos.Tutoriel'),
        ),
        migrations.AddField(
            model_name='note',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_utilisateur', to='guitutos.Tutoriel'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitutos.Utilisateur'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='com_tuto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitutos.Tutoriel'),
        ),
    ]
